name: Notify on Telegram

on:
  fork:
  push:
  release:
  issue_comment:
    types: created
  watch:
    types: started
  pull_request_review_comment:
    types: created
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, pinned, closed, reopened]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify the commit on Telegram My Group.
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
